package MonteCarlo.Osoby;

public enum StavyOsoby {
    PRICHOD,
    V_RADE_PRED_AUTOMATOM,
    ZADAVANIE_DO_AUTOMATU,
    KONIEC_ZADAVANIA_DO_AUTOMATU,
    V_RADE_PRED_OSBLUHOU,
    JE_OBSLUHOVANY,
    V_RADE_PRED_POKLADNOU,
    JE_OBSLUHOVANY_V_POKLADNI,
    IDE_SI_PRE_NADROZMERNY_TOVAR,
    ODCHADZA
}
